### ISSUE TITLE
Can a Config be wrapped with Variable?

### ISSUE THREAD

**Issue by dc3ea9f** [ZhiyuanChen/CHANfiG#16]
For now, I am using this code to get train_args.
```python
from chanfig import Config, Variable
from . import data as data_cfg


class BaseConfig(Config):
    def __init__(self) -> None:
        super().__init__()
        self.train_data: Config = data_cfg.ImageNet

    def get_train_args(self) -> Config:
        train_args: Config = Config({
            'data': self.train_data,
        })
        return train_args
```
Can the Config be wrapped with Variable such that we could do so?
```python
from chanfig import Config, Variable
from . import data as data_cfg


class BaseConfig(Config):
    def __init__(self) -> None:
        super().__init__()
        self.train_data: Config = data_cfg.ImageNet
        self.train_args: Config = Config({
            'data': self.train_data,
        })
```
and when run with `--train_data.name`, the `train_args.data.name` also changed?

**Comment by ZhiyuanChen** [comment]
This is actually a bug, or more precisely, two bugs.

1. If value is a `FlatDict` object, chanfig shouldn't make another copy. This is to ensure the consistency with python `dict`.
2. The following code should have worked

```python
from chanfig import Config, Variable
from . import data as data_cfg


class BaseConfig(Config):
    def __init__(self) -> None:
        super().__init__()
        self.train_data: Config = Variable(data_cfg.ImageNet)
        self.train_args: Config = Config({
            'data': self.train_data,
        })
```

Somehow merge did not recognised it correctly.

**Comment by ZhiyuanChen** [comment]
> 1. If value is a `FlatDict` object, chanfig shouldn't make another copy. This is to ensure the consistency with python `dict`.

Fixed now, will work on it next week.

**Comment by ZhiyuanChen** [comment]
Fixed in https://github.com/ZhiyuanChen/CHANfiG/commit/e62919a34f5e67e03f1ccdc812eddfdf4a95bf05
Please let me know if it works as expected
