### ISSUE TITLE
wrong output when use with rich.print

### ISSUE THREAD

**Issue by dc3ea9f** [ZhiyuanChen/CHANfiG#6]
Hi, thank you for your awesome project, while I notice there is a bug when using `rich.print`.

Test Code:
```python
from chanfig import Config
from rich import print as pprint


if __name__ == '__main__':
    config = Config(**{'hello': 'world'})
    print('print', config)
    pprint('rich.print', config)
    print(config.__rich__)
    print(config.keys())
```

Output:
```text
rint Config(<class 'chanfig.config.Config'>,
  ('hello'): 'world'
)
rich.print Config(<class 'chanfig.config.Config'>,
  ('hello'): 'world'
  ('__rich__'): Config(<class 'chanfig.config.Config'>, )
  ('aihwerij235234ljsdnp34ksodfipwoe234234jlskjdf'): Config(<class 'chanfig.config.Config'>, )
)
Config(<class 'chanfig.config.Config'>, )
dict_keys(['hello', '__rich__', 'aihwerij235234ljsdnp34ksodfipwoe234234jlskjdf'])
```

Expected behavior: `rich.print` should output the same with `print`.

I don't know if the weird behavior is caused by `rich` or `chanfig`, but it seems like the `rich.print` would inject some keys to my config. Hope you can help me fix this issue.

Thanks.

**Comment by ZhiyuanChen** [comment]
Thank you for reporting this.

Yes, the issue is resulted by `rich`. Since `Config` is a `DefaultDict`, when `rich` access keys does not in `Config`, CHANfiG will create an empty `Config`. 

I'll contact authors of `rich` to see if they are willing to add something similar to `_ipython_canary_method_should_not_exist_`to avoid this behaviour. 

In the meantime, if you `freeze` the `Config`, it won't create an empty `Config` when getting accessed. 

I also noted that the later item, `aihwerij235234ljsdnp34ksodfipwoe234234jlskjdf` is consistent across multiple runs, so if you are urgent, we can release a temporary fix for you before we can fix this issue.

**Comment by dc3ea9f** [comment]
Thank you for your kind response.

Though the `rich` would incorporate some annoyed keys into `Config`,  I believe this is not a big issue as the problems are resolved after `freeze`. I didn't try it yesterday since I am using small code snippets to be familiar with this library. :)

In my opinion, implementing a temporary fix seems unnecessary, and I remain hopeful that the authors of `rich` will address this bug in a future update.

**Comment by ZhiyuanChen** [comment]
No worries. 
Thank you for your feedback. I'll see what their plans are regarding this issue. 
You may also convert a `Config` object to `NestedDict` to resolve this issue without sacrificing the ability to modify its contents. 
Please let me know if you think any code sample/documentation could be helpful to you.

**Comment by dc3ea9f** [comment]
Note it.

I would post ideas to Discussions if there are any other valuable ideas or desired features.

Thanks.

**Comment by ZhiyuanChen** [comment]
> I would post ideas to Discussions if there are any other valuable ideas or desired features.

Thank you~ 

Since `rich` is not actively maintained, https://github.com/ZhiyuanChen/CHANfiG/commit/ad2ef51efdc64827d22cc175cf304e403b894c33 introduced a interim fix.

**Comment by dc3ea9f** [comment]
Good work! While I saw you introduced the `aihwerij235234ljsdnp34ksodfipwoe234234jlskjdf` as a magic string, maybe use `rich.protocol._GIBBERISH` is a better choice?

**Comment by ZhiyuanChen** [comment]
> Good work! While I saw you introduced the `aihwerij235234ljsdnp34ksodfipwoe234234jlskjdf` as a magic string, maybe use `rich.protocol._GIBBERISH` is a better choice? 

Yes, using `rich.protocol._GIBBERISH` could be better, but it involves adding a new dependency. 
This is a bit overkill in my opinion.

**Comment by ZhiyuanChen** [comment]
Haha, no worries~
